// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewLeaderboard.Data;

#nullable disable

namespace NewLeaderboard.Migrations
{
    [DbContext(typeof(NewLeaderboardContext))]
    partial class NewLeaderboardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewLeaderboard.Models.Rank", b =>
                {
                    b.Property<int>("RankID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankID"), 1L, 1);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RankID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("NewLeaderboard.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NewLeaderboard.Models.Rank", b =>
                {
                    b.HasOne("NewLeaderboard.Models.User", "UserObj")
                        .WithOne("Rank")
                        .HasForeignKey("NewLeaderboard.Models.Rank", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("NewLeaderboard.Models.User", b =>
                {
                    b.Navigation("Rank");
                });
#pragma warning restore 612, 618
        }
    }
}
